// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSb6hDKwjh9QLX9Jo_qdZo_BVfgFebUqo',
    appId: '1:700099258867:web:4a1745d8580f1eeb1b8a86',
    messagingSenderId: '700099258867',
    projectId: 'payal-creation',
    authDomain: 'payal-creation.firebaseapp.com',
    storageBucket: 'payal-creation.firebasestorage.app',
    measurementId: 'G-7CBXW4TFXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVcLrHoLMTi5tBvt-zuUumi_omZMSiaPg',
    appId: '1:700099258867:android:341e932da89090f71b8a86',
    messagingSenderId: '700099258867',
    projectId: 'payal-creation',
    storageBucket: 'payal-creation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN2JhZVhK7eC-Q9UZeuzB79u4mbzOB4qw',
    appId: '1:700099258867:ios:b50ad44b8cfa78fc1b8a86',
    messagingSenderId: '700099258867',
    projectId: 'payal-creation',
    storageBucket: 'payal-creation.firebasestorage.app',
    iosBundleId: 'com.example.payalCreation',
  );
}
