name: Implementing Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-Latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4
  
      - name: Install flutter
        uses: subosito/flutter-action@v2
        

      - name: Install dependencies
        run: flutter pub get
  
      - name: Run tests
        run: flutter test
  
      - name: Build web app
        run: flutter build web

      - name: Build web app
        run: flutter build web

      - name: Build Docker image
        run: docker build -t payal-creation-web:ci .